camera:
  index: 0
  width: null
  height: null

detector:
  model_path: robot/cv_models/yolo11_nano_80EP.pt
  img_size: 640
  confidence_threshold: 0.5
  inference_hz: 12
  min_consecutive_detections: 10
  hold_seconds: 1